language: node_js
node_js:
  - "10"
  - "12"
cache:
  npm: true
  directories:
    - ./node_modules
  override:
    - npx cypress verify
before_install:
  - npm i -g npm@6.13.4
before_script:
  - npm run build
script:
  - npm run lint
  - npm run lint:css
